services:
  # Frontend Static Site
  - type: web
    name: burnlist-frontend
    env: static
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production

  # Backend API Service
  - type: web
    name: burnlist-api
    env: node
    nodeVersion: 18
    buildCommand: npm ci --include=dev
    startCommand: node finviz-api-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FINVIZ_API_TOKEN
        sync: false
    healthCheckPath: /api/health