services:
  # Frontend Web Service
  - type: web
    name: burnlist-frontend
    env: node
    nodeVersion: 18
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  # Backend API Service
  - type: web
    name: burnlist-api
    env: node
    nodeVersion: 18
    buildCommand: npm ci --include=dev
    startCommand: node finviz-api-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FINVIZ_API_TOKEN
        sync: false
    healthCheckPath: /api/health