services:
  # Combined Web Service (frontend + API)
  - type: web
    name: burnlist-app
    env: node
    nodeVersion: 18
    buildCommand: rm -rf node_modules package-lock.json && npm install --include=dev && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FINVIZ_API_TOKEN
        sync: false
    healthCheckPath: /