services:
  # Frontend Web Service (instead of Static Site)
  - type: web
    name: burnlist-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -p $PORT --single
    envVars:
      - key: NODE_ENV
        value: production

  # Backend API Service
  - type: web
    name: burnlist-api
    env: node
    buildCommand: npm install
    startCommand: node finviz-api-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FINVIZ_API_TOKEN
        sync: false