services:
  # Frontend Static Site
  - type: web
    name: burnlist-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://burnlist-api.onrender.com;"
      - path: /*
        name: X-Frame-Options
        value: "DENY"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://burnlist-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service
  - type: web
    name: burnlist-api
    env: node
    buildCommand: npm install
    startCommand: node finviz-api-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: FINVIZ_API_TOKEN
        sync: false